#!/bin/bash

set -eu pipefail;

echo "Starting program.";

((nslookup google.com | grep "SERVFAIL") && echo "SERVFAIL detected!") || exit 0;

if [[ -f /etc/resolv.conf ]]; then
    echo "Found resolv.conf!";
    echo "#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search lan
nameserver 1.1.1.1";

systemctl restart network
fi
